# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -I. -Iengine -Iengine/platform/Vulkan -Ivendor -Ivendor/glfw/include -Ivendor/stb -Ivendor/glm -Ivendor/imgui -Ivendor/imGuizmo -Ivendor/spdlog/include -Ivendor/shaderc/libshaderc/include/shaderc -Ivendor/shaderc/libshaderc/include -Ivendor/assetImporter/include -Ivendor/fastgltf/include -Ivendor/yaml-cpp/include -Ivendor/tinyObjLoader -Ivendor/box2d/include -Ivendor/entt/include -Ivendor/tinygltf -Ivendor/simdjson -Ivendor/json -Ivendor/sdl/include -Ivendor/sdl_mixer/include -Ivendor/thread-pool/include -Ivendor/tracy/include -I/usr/include -Ivendor/pamanager/libpamanager/src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/glib-2.0/include -I/usr/lib64/glib-2.0/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/libengine.a
OBJDIR = bin-int/Debug/Debug/engine
DEFINES += -DENGINE_VERSION=\"0.9.0\" -DPULSEAUDIO -DLINUX -DDEBUG -DPROFILING -DTRACY_ENABLE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -ggdb -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20 -ggdb -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -fno-pie -no-pie

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/libengine.a
OBJDIR = bin-int/Release/Release/engine
DEFINES += -DENGINE_VERSION=\"0.9.0\" -DPULSEAUDIO -DLINUX -DNDEBUG -DPROFILING -DTRACY_ENABLE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s -fno-pie -no-pie

else ifeq ($(config),dist)
TARGETDIR = bin/Dist
TARGET = $(TARGETDIR)/libengine.a
OBJDIR = bin-int/Dist/Dist/engine
DEFINES += -DENGINE_VERSION=\"0.9.0\" -DPULSEAUDIO -DLINUX -DNDEBUG -DDISTRIBUTION_BUILD
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s -fno-pie -no-pie

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/ImGuizmo.o
GENERATED += $(OBJDIR)/SDLaudio.o
GENERATED += $(OBJDIR)/SDLinput.o
GENERATED += $(OBJDIR)/TracyClient.o
GENERATED += $(OBJDIR)/UIscreen.o
GENERATED += $(OBJDIR)/VKbloomAttachments.o
GENERATED += $(OBJDIR)/VKbloomFrameBuffer.o
GENERATED += $(OBJDIR)/VKbloomRenderPass.o
GENERATED += $(OBJDIR)/VKbloomRenderSystem.o
GENERATED += $(OBJDIR)/VKbuffer.o
GENERATED += $(OBJDIR)/VKcore.o
GENERATED += $(OBJDIR)/VKcubemap.o
GENERATED += $(OBJDIR)/VKcubemapRenderSys.o
GENERATED += $(OBJDIR)/VKcursor.o
GENERATED += $(OBJDIR)/VKdebugRenderSys.o
GENERATED += $(OBJDIR)/VKdeferredShading.o
GENERATED += $(OBJDIR)/VKdescriptor.o
GENERATED += $(OBJDIR)/VKdevice.o
GENERATED += $(OBJDIR)/VKgraphicsContext.o
GENERATED += $(OBJDIR)/VKgrassSys.o
GENERATED += $(OBJDIR)/VKguiRenderSys.o
GENERATED += $(OBJDIR)/VKimgui.o
GENERATED += $(OBJDIR)/VKinput.o
GENERATED += $(OBJDIR)/VKinstanceBuffer.o
GENERATED += $(OBJDIR)/VKlightSys.o
GENERATED += $(OBJDIR)/VKmaterialDescriptor.o
GENERATED += $(OBJDIR)/VKmodel.o
GENERATED += $(OBJDIR)/VKpbrSASys.o
GENERATED += $(OBJDIR)/VKpbrSys.o
GENERATED += $(OBJDIR)/VKpipeline.o
GENERATED += $(OBJDIR)/VKpool.o
GENERATED += $(OBJDIR)/VKpostprocessingSys.o
GENERATED += $(OBJDIR)/VKrenderPass.o
GENERATED += $(OBJDIR)/VKrenderer.o
GENERATED += $(OBJDIR)/VKresourceDescriptor.o
GENERATED += $(OBJDIR)/VKshader.o
GENERATED += $(OBJDIR)/VKshadowAnimatedRenderSysInstanced.o
GENERATED += $(OBJDIR)/VKshadowMap.o
GENERATED += $(OBJDIR)/VKshadowRenderSysInstanced.o
GENERATED += $(OBJDIR)/VKspriteRenderSys.o
GENERATED += $(OBJDIR)/VKspriteRenderSys2D.o
GENERATED += $(OBJDIR)/VKswapChain.o
GENERATED += $(OBJDIR)/VKtexture.o
GENERATED += $(OBJDIR)/VKwindow.o
GENERATED += $(OBJDIR)/audio.o
GENERATED += $(OBJDIR)/buffer.o
GENERATED += $(OBJDIR)/builder.o
GENERATED += $(OBJDIR)/camera.o
GENERATED += $(OBJDIR)/cameraController.o
GENERATED += $(OBJDIR)/common.o
GENERATED += $(OBJDIR)/components.o
GENERATED += $(OBJDIR)/context.o
GENERATED += $(OBJDIR)/controller.o
GENERATED += $(OBJDIR)/controllerConfiguration.o
GENERATED += $(OBJDIR)/core.o
GENERATED += $(OBJDIR)/coreSettings.o
GENERATED += $(OBJDIR)/cubemap.o
GENERATED += $(OBJDIR)/cursor.o
GENERATED += $(OBJDIR)/curves.o
GENERATED += $(OBJDIR)/dictionary.o
GENERATED += $(OBJDIR)/dirListing.o
GENERATED += $(OBJDIR)/drawBuffer.o
GENERATED += $(OBJDIR)/engine.o
GENERATED += $(OBJDIR)/fastgltfBuilder.o
GENERATED += $(OBJDIR)/fastgltfModelSA.o
GENERATED += $(OBJDIR)/fbxBuilder.o
GENERATED += $(OBJDIR)/fbxModelSA.o
GENERATED += $(OBJDIR)/file.o
GENERATED += $(OBJDIR)/gltfBuilder.o
GENERATED += $(OBJDIR)/gltfModelSA.o
GENERATED += $(OBJDIR)/graphicsContext.o
GENERATED += $(OBJDIR)/i18n.o
GENERATED += $(OBJDIR)/image.o
GENERATED += $(OBJDIR)/imgui.o
GENERATED += $(OBJDIR)/imgui1.o
GENERATED += $(OBJDIR)/imgui_demo.o
GENERATED += $(OBJDIR)/imgui_draw.o
GENERATED += $(OBJDIR)/imgui_impl_glfw.o
GENERATED += $(OBJDIR)/imgui_impl_vulkan.o
GENERATED += $(OBJDIR)/imgui_tables.o
GENERATED += $(OBJDIR)/imgui_widgets.o
GENERATED += $(OBJDIR)/instanceBuffer.o
GENERATED += $(OBJDIR)/instrumentation.o
GENERATED += $(OBJDIR)/layer.o
GENERATED += $(OBJDIR)/layerStack.o
GENERATED += $(OBJDIR)/log.o
GENERATED += $(OBJDIR)/materialDescriptor.o
GENERATED += $(OBJDIR)/math.o
GENERATED += $(OBJDIR)/model.o
GENERATED += $(OBJDIR)/nativeScript.o
GENERATED += $(OBJDIR)/particleSystem.o
GENERATED += $(OBJDIR)/path.o
GENERATED += $(OBJDIR)/pathBrowser.o
GENERATED += $(OBJDIR)/random.o
GENERATED += $(OBJDIR)/registry.o
GENERATED += $(OBJDIR)/rendererAPI.o
GENERATED += $(OBJDIR)/resourceDescriptor.o
GENERATED += $(OBJDIR)/resources.o
GENERATED += $(OBJDIR)/root.o
GENERATED += $(OBJDIR)/scene.o
GENERATED += $(OBJDIR)/sceneGraph.o
GENERATED += $(OBJDIR)/sceneLoader.o
GENERATED += $(OBJDIR)/sceneLoaderDeserializeJSON.o
GENERATED += $(OBJDIR)/sceneLoaderSerializeJSON.o
GENERATED += $(OBJDIR)/screen.o
GENERATED += $(OBJDIR)/settings.o
GENERATED += $(OBJDIR)/simdjson.o
GENERATED += $(OBJDIR)/skeletalAnimation.o
GENERATED += $(OBJDIR)/skeletalAnimations.o
GENERATED += $(OBJDIR)/skeleton.o
GENERATED += $(OBJDIR)/sound.o
GENERATED += $(OBJDIR)/sprite.o
GENERATED += $(OBJDIR)/spriteAnimation.o
GENERATED += $(OBJDIR)/spritesheet.o
GENERATED += $(OBJDIR)/stb_image.o
GENERATED += $(OBJDIR)/stringUtils.o
GENERATED += $(OBJDIR)/terrainBuilder.o
GENERATED += $(OBJDIR)/terrainLoaderDeserializeJSON.o
GENERATED += $(OBJDIR)/texture.o
GENERATED += $(OBJDIR)/textureAtlas.o
GENERATED += $(OBJDIR)/threadPool.o
GENERATED += $(OBJDIR)/threadUtil.o
GENERATED += $(OBJDIR)/timer.o
GENERATED += $(OBJDIR)/timestep.o
GENERATED += $(OBJDIR)/tiny_gltf.o
GENERATED += $(OBJDIR)/transformation.o
GENERATED += $(OBJDIR)/tween.o
GENERATED += $(OBJDIR)/ufbxBuilder.o
GENERATED += $(OBJDIR)/ufbxModelSA.o
GENERATED += $(OBJDIR)/utf8.o
GENERATED += $(OBJDIR)/view.o
GENERATED += $(OBJDIR)/viewGroup.o
GENERATED += $(OBJDIR)/window.o
GENERATED += $(OBJDIR)/wrapText.o
OBJECTS += $(OBJDIR)/ImGuizmo.o
OBJECTS += $(OBJDIR)/SDLaudio.o
OBJECTS += $(OBJDIR)/SDLinput.o
OBJECTS += $(OBJDIR)/TracyClient.o
OBJECTS += $(OBJDIR)/UIscreen.o
OBJECTS += $(OBJDIR)/VKbloomAttachments.o
OBJECTS += $(OBJDIR)/VKbloomFrameBuffer.o
OBJECTS += $(OBJDIR)/VKbloomRenderPass.o
OBJECTS += $(OBJDIR)/VKbloomRenderSystem.o
OBJECTS += $(OBJDIR)/VKbuffer.o
OBJECTS += $(OBJDIR)/VKcore.o
OBJECTS += $(OBJDIR)/VKcubemap.o
OBJECTS += $(OBJDIR)/VKcubemapRenderSys.o
OBJECTS += $(OBJDIR)/VKcursor.o
OBJECTS += $(OBJDIR)/VKdebugRenderSys.o
OBJECTS += $(OBJDIR)/VKdeferredShading.o
OBJECTS += $(OBJDIR)/VKdescriptor.o
OBJECTS += $(OBJDIR)/VKdevice.o
OBJECTS += $(OBJDIR)/VKgraphicsContext.o
OBJECTS += $(OBJDIR)/VKgrassSys.o
OBJECTS += $(OBJDIR)/VKguiRenderSys.o
OBJECTS += $(OBJDIR)/VKimgui.o
OBJECTS += $(OBJDIR)/VKinput.o
OBJECTS += $(OBJDIR)/VKinstanceBuffer.o
OBJECTS += $(OBJDIR)/VKlightSys.o
OBJECTS += $(OBJDIR)/VKmaterialDescriptor.o
OBJECTS += $(OBJDIR)/VKmodel.o
OBJECTS += $(OBJDIR)/VKpbrSASys.o
OBJECTS += $(OBJDIR)/VKpbrSys.o
OBJECTS += $(OBJDIR)/VKpipeline.o
OBJECTS += $(OBJDIR)/VKpool.o
OBJECTS += $(OBJDIR)/VKpostprocessingSys.o
OBJECTS += $(OBJDIR)/VKrenderPass.o
OBJECTS += $(OBJDIR)/VKrenderer.o
OBJECTS += $(OBJDIR)/VKresourceDescriptor.o
OBJECTS += $(OBJDIR)/VKshader.o
OBJECTS += $(OBJDIR)/VKshadowAnimatedRenderSysInstanced.o
OBJECTS += $(OBJDIR)/VKshadowMap.o
OBJECTS += $(OBJDIR)/VKshadowRenderSysInstanced.o
OBJECTS += $(OBJDIR)/VKspriteRenderSys.o
OBJECTS += $(OBJDIR)/VKspriteRenderSys2D.o
OBJECTS += $(OBJDIR)/VKswapChain.o
OBJECTS += $(OBJDIR)/VKtexture.o
OBJECTS += $(OBJDIR)/VKwindow.o
OBJECTS += $(OBJDIR)/audio.o
OBJECTS += $(OBJDIR)/buffer.o
OBJECTS += $(OBJDIR)/builder.o
OBJECTS += $(OBJDIR)/camera.o
OBJECTS += $(OBJDIR)/cameraController.o
OBJECTS += $(OBJDIR)/common.o
OBJECTS += $(OBJDIR)/components.o
OBJECTS += $(OBJDIR)/context.o
OBJECTS += $(OBJDIR)/controller.o
OBJECTS += $(OBJDIR)/controllerConfiguration.o
OBJECTS += $(OBJDIR)/core.o
OBJECTS += $(OBJDIR)/coreSettings.o
OBJECTS += $(OBJDIR)/cubemap.o
OBJECTS += $(OBJDIR)/cursor.o
OBJECTS += $(OBJDIR)/curves.o
OBJECTS += $(OBJDIR)/dictionary.o
OBJECTS += $(OBJDIR)/dirListing.o
OBJECTS += $(OBJDIR)/drawBuffer.o
OBJECTS += $(OBJDIR)/engine.o
OBJECTS += $(OBJDIR)/fastgltfBuilder.o
OBJECTS += $(OBJDIR)/fastgltfModelSA.o
OBJECTS += $(OBJDIR)/fbxBuilder.o
OBJECTS += $(OBJDIR)/fbxModelSA.o
OBJECTS += $(OBJDIR)/file.o
OBJECTS += $(OBJDIR)/gltfBuilder.o
OBJECTS += $(OBJDIR)/gltfModelSA.o
OBJECTS += $(OBJDIR)/graphicsContext.o
OBJECTS += $(OBJDIR)/i18n.o
OBJECTS += $(OBJDIR)/image.o
OBJECTS += $(OBJDIR)/imgui.o
OBJECTS += $(OBJDIR)/imgui1.o
OBJECTS += $(OBJDIR)/imgui_demo.o
OBJECTS += $(OBJDIR)/imgui_draw.o
OBJECTS += $(OBJDIR)/imgui_impl_glfw.o
OBJECTS += $(OBJDIR)/imgui_impl_vulkan.o
OBJECTS += $(OBJDIR)/imgui_tables.o
OBJECTS += $(OBJDIR)/imgui_widgets.o
OBJECTS += $(OBJDIR)/instanceBuffer.o
OBJECTS += $(OBJDIR)/instrumentation.o
OBJECTS += $(OBJDIR)/layer.o
OBJECTS += $(OBJDIR)/layerStack.o
OBJECTS += $(OBJDIR)/log.o
OBJECTS += $(OBJDIR)/materialDescriptor.o
OBJECTS += $(OBJDIR)/math.o
OBJECTS += $(OBJDIR)/model.o
OBJECTS += $(OBJDIR)/nativeScript.o
OBJECTS += $(OBJDIR)/particleSystem.o
OBJECTS += $(OBJDIR)/path.o
OBJECTS += $(OBJDIR)/pathBrowser.o
OBJECTS += $(OBJDIR)/random.o
OBJECTS += $(OBJDIR)/registry.o
OBJECTS += $(OBJDIR)/rendererAPI.o
OBJECTS += $(OBJDIR)/resourceDescriptor.o
OBJECTS += $(OBJDIR)/resources.o
OBJECTS += $(OBJDIR)/root.o
OBJECTS += $(OBJDIR)/scene.o
OBJECTS += $(OBJDIR)/sceneGraph.o
OBJECTS += $(OBJDIR)/sceneLoader.o
OBJECTS += $(OBJDIR)/sceneLoaderDeserializeJSON.o
OBJECTS += $(OBJDIR)/sceneLoaderSerializeJSON.o
OBJECTS += $(OBJDIR)/screen.o
OBJECTS += $(OBJDIR)/settings.o
OBJECTS += $(OBJDIR)/simdjson.o
OBJECTS += $(OBJDIR)/skeletalAnimation.o
OBJECTS += $(OBJDIR)/skeletalAnimations.o
OBJECTS += $(OBJDIR)/skeleton.o
OBJECTS += $(OBJDIR)/sound.o
OBJECTS += $(OBJDIR)/sprite.o
OBJECTS += $(OBJDIR)/spriteAnimation.o
OBJECTS += $(OBJDIR)/spritesheet.o
OBJECTS += $(OBJDIR)/stb_image.o
OBJECTS += $(OBJDIR)/stringUtils.o
OBJECTS += $(OBJDIR)/terrainBuilder.o
OBJECTS += $(OBJDIR)/terrainLoaderDeserializeJSON.o
OBJECTS += $(OBJDIR)/texture.o
OBJECTS += $(OBJDIR)/textureAtlas.o
OBJECTS += $(OBJDIR)/threadPool.o
OBJECTS += $(OBJDIR)/threadUtil.o
OBJECTS += $(OBJDIR)/timer.o
OBJECTS += $(OBJDIR)/timestep.o
OBJECTS += $(OBJDIR)/tiny_gltf.o
OBJECTS += $(OBJDIR)/transformation.o
OBJECTS += $(OBJDIR)/tween.o
OBJECTS += $(OBJDIR)/ufbxBuilder.o
OBJECTS += $(OBJDIR)/ufbxModelSA.o
OBJECTS += $(OBJDIR)/utf8.o
OBJECTS += $(OBJDIR)/view.o
OBJECTS += $(OBJDIR)/viewGroup.o
OBJECTS += $(OBJDIR)/window.o
OBJECTS += $(OBJDIR)/wrapText.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking engine
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning engine
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/audio.o: engine/audio/audio.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sound.o: engine/audio/sound.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TracyClient.o: engine/auxiliary/TracyClient.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/file.o: engine/auxiliary/file.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/instrumentation.o: engine/auxiliary/instrumentation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/math.o: engine/auxiliary/math.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/random.o: engine/auxiliary/random.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/threadPool.o: engine/auxiliary/threadPool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/timestep.o: engine/auxiliary/timestep.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/core.o: engine/core.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/coreSettings.o: engine/coreSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/engine.o: engine/engine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i18n.o: engine/gui/Common/Data/Text/i18n.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utf8.o: engine/gui/Common/Data/Text/utf8.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wrapText.o: engine/gui/Common/Data/Text/wrapText.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dirListing.o: engine/gui/Common/File/dirListing.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/path.o: engine/gui/Common/File/path.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pathBrowser.o: engine/gui/Common/File/pathBrowser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/curves.o: engine/gui/Common/Math/curves.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/drawBuffer.o: engine/gui/Common/Render/drawBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/threadUtil.o: engine/gui/Common/Thread/threadUtil.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UIscreen.o: engine/gui/Common/UI/UIscreen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/context.o: engine/gui/Common/UI/context.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/root.o: engine/gui/Common/UI/root.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/screen.o: engine/gui/Common/UI/screen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tween.o: engine/gui/Common/UI/tween.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/view.o: engine/gui/Common/UI/view.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/viewGroup.o: engine/gui/Common/UI/viewGroup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stringUtils.o: engine/gui/Common/stringUtils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/textureAtlas.o: engine/gui/Render/textureAtlas.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/common.o: engine/gui/common.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/layer.o: engine/layer/layer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/layerStack.o: engine/layer/layerStack.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/log.o: engine/log/log.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SDLaudio.o: engine/platform/SDL/SDLaudio.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SDLinput.o: engine/platform/SDL/SDLinput.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/controller.o: engine/platform/SDL/controller.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/controllerConfiguration.o: engine/platform/SDL/controllerConfiguration.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/timer.o: engine/platform/SDL/timer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKbuffer.o: engine/platform/Vulkan/VKbuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKcore.o: engine/platform/Vulkan/VKcore.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKcubemap.o: engine/platform/Vulkan/VKcubemap.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKcursor.o: engine/platform/Vulkan/VKcursor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKdescriptor.o: engine/platform/Vulkan/VKdescriptor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKdevice.o: engine/platform/Vulkan/VKdevice.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKgraphicsContext.o: engine/platform/Vulkan/VKgraphicsContext.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKinput.o: engine/platform/Vulkan/VKinput.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKinstanceBuffer.o: engine/platform/Vulkan/VKinstanceBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKmaterialDescriptor.o: engine/platform/Vulkan/VKmaterialDescriptor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKmodel.o: engine/platform/Vulkan/VKmodel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKpipeline.o: engine/platform/Vulkan/VKpipeline.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKpool.o: engine/platform/Vulkan/VKpool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKrenderPass.o: engine/platform/Vulkan/VKrenderPass.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKrenderer.o: engine/platform/Vulkan/VKrenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKresourceDescriptor.o: engine/platform/Vulkan/VKresourceDescriptor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKshader.o: engine/platform/Vulkan/VKshader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKshadowMap.o: engine/platform/Vulkan/VKshadowMap.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKswapChain.o: engine/platform/Vulkan/VKswapChain.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKtexture.o: engine/platform/Vulkan/VKtexture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKwindow.o: engine/platform/Vulkan/VKwindow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKimgui.o: engine/platform/Vulkan/imguiEngine/VKimgui.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui.o: engine/platform/Vulkan/imguiEngine/imgui.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKcubemapRenderSys.o: engine/platform/Vulkan/systems/VKcubemapRenderSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKdebugRenderSys.o: engine/platform/Vulkan/systems/VKdebugRenderSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKdeferredShading.o: engine/platform/Vulkan/systems/VKdeferredShading.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKgrassSys.o: engine/platform/Vulkan/systems/VKgrassSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKguiRenderSys.o: engine/platform/Vulkan/systems/VKguiRenderSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKlightSys.o: engine/platform/Vulkan/systems/VKlightSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKpbrSASys.o: engine/platform/Vulkan/systems/VKpbrSASys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKpbrSys.o: engine/platform/Vulkan/systems/VKpbrSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKpostprocessingSys.o: engine/platform/Vulkan/systems/VKpostprocessingSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKshadowAnimatedRenderSysInstanced.o: engine/platform/Vulkan/systems/VKshadowAnimatedRenderSysInstanced.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKshadowRenderSysInstanced.o: engine/platform/Vulkan/systems/VKshadowRenderSysInstanced.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKspriteRenderSys.o: engine/platform/Vulkan/systems/VKspriteRenderSys.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKspriteRenderSys2D.o: engine/platform/Vulkan/systems/VKspriteRenderSys2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKbloomAttachments.o: engine/platform/Vulkan/systems/bloom/VKbloomAttachments.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKbloomFrameBuffer.o: engine/platform/Vulkan/systems/bloom/VKbloomFrameBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKbloomRenderPass.o: engine/platform/Vulkan/systems/bloom/VKbloomRenderPass.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VKbloomRenderSystem.o: engine/platform/Vulkan/systems/bloom/VKbloomRenderSystem.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/window.o: engine/platform/window.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/buffer.o: engine/renderer/buffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/builder.o: engine/renderer/builder/builder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fastgltfBuilder.o: engine/renderer/builder/fastgltfBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fbxBuilder.o: engine/renderer/builder/fbxBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gltfBuilder.o: engine/renderer/builder/gltfBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/terrainBuilder.o: engine/renderer/builder/terrainBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ufbxBuilder.o: engine/renderer/builder/ufbxBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/camera.o: engine/renderer/camera.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cameraController.o: engine/renderer/cameraController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cubemap.o: engine/renderer/cubemap.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cursor.o: engine/renderer/cursor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/graphicsContext.o: engine/renderer/graphicsContext.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/image.o: engine/renderer/image.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/instanceBuffer.o: engine/renderer/instanceBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/materialDescriptor.o: engine/renderer/materialDescriptor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/model.o: engine/renderer/model.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rendererAPI.o: engine/renderer/rendererAPI.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/resourceDescriptor.o: engine/renderer/resourceDescriptor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fastgltfModelSA.o: engine/renderer/skeletalAnimation/fastgltfModelSA.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fbxModelSA.o: engine/renderer/skeletalAnimation/fbxModelSA.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gltfModelSA.o: engine/renderer/skeletalAnimation/gltfModelSA.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/skeletalAnimation.o: engine/renderer/skeletalAnimation/skeletalAnimation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/skeletalAnimations.o: engine/renderer/skeletalAnimation/skeletalAnimations.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/skeleton.o: engine/renderer/skeletalAnimation/skeleton.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ufbxModelSA.o: engine/renderer/skeletalAnimation/ufbxModelSA.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/texture.o: engine/renderer/texture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/components.o: engine/scene/components.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dictionary.o: engine/scene/dictionary.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/nativeScript.o: engine/scene/nativeScript.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/particleSystem.o: engine/scene/particleSystem.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/registry.o: engine/scene/registry.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scene.o: engine/scene/scene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sceneGraph.o: engine/scene/sceneGraph.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sceneLoader.o: engine/scene/sceneLoader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sceneLoaderDeserializeJSON.o: engine/scene/sceneLoaderDeserializeJSON.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sceneLoaderSerializeJSON.o: engine/scene/sceneLoaderSerializeJSON.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/terrainLoaderDeserializeJSON.o: engine/scene/terrainLoaderDeserializeJSON.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/settings.o: engine/settings/settings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sprite.o: engine/sprite/sprite.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spriteAnimation.o: engine/sprite/spriteAnimation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spritesheet.o: engine/sprite/spritesheet.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/transformation.o: engine/transform/transformation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/resources.o: resources/resources.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuizmo.o: vendor/imGuizmo/ImGuizmo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_impl_glfw.o: vendor/imgui/backends/imgui_impl_glfw.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_impl_vulkan.o: vendor/imgui/backends/imgui_impl_vulkan.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui1.o: vendor/imgui/imgui.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_demo.o: vendor/imgui/imgui_demo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_draw.o: vendor/imgui/imgui_draw.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_tables.o: vendor/imgui/imgui_tables.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/simdjson.o: vendor/simdjson/simdjson.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stb_image.o: vendor/stb/stb_image.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tiny_gltf.o: vendor/tinygltf/tiny_gltf.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif