# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -I. -Iapplication -Iapplication/lucre -Iengine -Ivendor -Ivendor/imgui -Iresources -Ivendor/spdlog/include -Ivendor/yaml-cpp/include -Ivendor/fastgltf/include -Ivendor/assetImporter/include -Ivendor/tinyObjLoader -Ivendor/box2d/include -Ivendor/entt/include -Ivendor/simdjson -Ivendor/json -Ivendor/glm -Ivendor/stb -Ivendor/thread-pool/include -Ivendor/tracy/include -Ivendor/pamanager/libpamanager/src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/glib-2.0/include -I/usr/lib64/glib-2.0/include -Ivendor/sdl/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/lucre
OBJDIR = bin-int/Debug/Debug/lucre
DEFINES += -DLUCRE_VERSION=\"0.4.2\" -DPULSEAUDIO -DLINUX -DDEBUG -DPROFILING -DTRACY_ENABLE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -ggdb -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20 -ggdb -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
LIBS += bin/Debug/libengine.a vendor/yaml-cpp/build/libyaml-cpp.a vendor/fastgltf/bin/Debug/libfastgltf.a vendor/ufbx/bin/Debug/libufbx.a vendor/box2d/bin/Debug/libbox2d.a vendor/shaderc/bin/shaderc/libshaderc.a vendor/shaderc/bin/shaderc_util/libshaderc_util.a vendor/shaderc/bin/SPIRV-Tools-opt/libSPIRV-Tools-opt.a vendor/shaderc/bin/SPIRV-Tools/libSPIRV-Tools.a vendor/shaderc/bin/MachineIndependent/libMachineIndependent.a vendor/shaderc/bin/OSDependent/libOSDependent.a vendor/shaderc/bin/GenericCodeGen/libGenericCodeGen.a vendor/shaderc/bin/OGLCompiler/libOGLCompiler.a vendor/shaderc/bin/SPIRV/libSPIRV.a vendor/assetImporter/bin/Debug/libassetImporter.a vendor/assetImporter/bin/Debug/libzlibstatic.a vendor/pamanager/libpamanager/bin/Debug/liblibpamanager.a vendor/sdl_mixer/build/Debug/libsdl_mixer.a vendor/sdl/build/gmake2--Debug/libsdl.a vendor/sdl_mixer/build/Debug/liblibvorbis.a vendor/sdl_mixer/build/Debug/liblibogg.a vendor/glfw/build/src/libglfw3.a bin/Debug/libresource-system-gnu.a -lm -ldl -lvulkan -lpthread -lX11 -lXrandr -lXi -lpulse -lglib-2.0 -lgio-2.0
LDDEPS += bin/Debug/libengine.a vendor/yaml-cpp/build/libyaml-cpp.a vendor/fastgltf/bin/Debug/libfastgltf.a vendor/ufbx/bin/Debug/libufbx.a vendor/box2d/bin/Debug/libbox2d.a vendor/shaderc/bin/shaderc/libshaderc.a vendor/shaderc/bin/shaderc_util/libshaderc_util.a vendor/shaderc/bin/SPIRV-Tools-opt/libSPIRV-Tools-opt.a vendor/shaderc/bin/SPIRV-Tools/libSPIRV-Tools.a vendor/shaderc/bin/MachineIndependent/libMachineIndependent.a vendor/shaderc/bin/OSDependent/libOSDependent.a vendor/shaderc/bin/GenericCodeGen/libGenericCodeGen.a vendor/shaderc/bin/OGLCompiler/libOGLCompiler.a vendor/shaderc/bin/SPIRV/libSPIRV.a vendor/assetImporter/bin/Debug/libassetImporter.a vendor/assetImporter/bin/Debug/libzlibstatic.a vendor/pamanager/libpamanager/bin/Debug/liblibpamanager.a vendor/sdl_mixer/build/Debug/libsdl_mixer.a vendor/sdl/build/gmake2--Debug/libsdl.a vendor/sdl_mixer/build/Debug/liblibvorbis.a vendor/sdl_mixer/build/Debug/liblibogg.a vendor/glfw/build/src/libglfw3.a bin/Debug/libresource-system-gnu.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -fno-pie -no-pie

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/lucre
OBJDIR = bin-int/Release/Release/lucre
DEFINES += -DLUCRE_VERSION=\"0.4.2\" -DPULSEAUDIO -DLINUX -DNDEBUG -DPROFILING -DTRACY_ENABLE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
LIBS += bin/Release/libengine.a vendor/yaml-cpp/build/libyaml-cpp.a vendor/fastgltf/bin/Release/libfastgltf.a vendor/ufbx/bin/Release/libufbx.a vendor/box2d/bin/Release/libbox2d.a vendor/shaderc/bin/shaderc/libshaderc.a vendor/shaderc/bin/shaderc_util/libshaderc_util.a vendor/shaderc/bin/SPIRV-Tools-opt/libSPIRV-Tools-opt.a vendor/shaderc/bin/SPIRV-Tools/libSPIRV-Tools.a vendor/shaderc/bin/MachineIndependent/libMachineIndependent.a vendor/shaderc/bin/OSDependent/libOSDependent.a vendor/shaderc/bin/GenericCodeGen/libGenericCodeGen.a vendor/shaderc/bin/OGLCompiler/libOGLCompiler.a vendor/shaderc/bin/SPIRV/libSPIRV.a vendor/assetImporter/bin/Release/libassetImporter.a vendor/assetImporter/bin/Release/libzlibstatic.a vendor/pamanager/libpamanager/bin/Release/liblibpamanager.a vendor/sdl_mixer/build/Release/libsdl_mixer.a vendor/sdl/build/gmake2--Release/libsdl.a vendor/sdl_mixer/build/Release/liblibvorbis.a vendor/sdl_mixer/build/Release/liblibogg.a vendor/glfw/build/src/libglfw3.a bin/Release/libresource-system-gnu.a -lm -ldl -lvulkan -lpthread -lX11 -lXrandr -lXi -lpulse -lglib-2.0 -lgio-2.0
LDDEPS += bin/Release/libengine.a vendor/yaml-cpp/build/libyaml-cpp.a vendor/fastgltf/bin/Release/libfastgltf.a vendor/ufbx/bin/Release/libufbx.a vendor/box2d/bin/Release/libbox2d.a vendor/shaderc/bin/shaderc/libshaderc.a vendor/shaderc/bin/shaderc_util/libshaderc_util.a vendor/shaderc/bin/SPIRV-Tools-opt/libSPIRV-Tools-opt.a vendor/shaderc/bin/SPIRV-Tools/libSPIRV-Tools.a vendor/shaderc/bin/MachineIndependent/libMachineIndependent.a vendor/shaderc/bin/OSDependent/libOSDependent.a vendor/shaderc/bin/GenericCodeGen/libGenericCodeGen.a vendor/shaderc/bin/OGLCompiler/libOGLCompiler.a vendor/shaderc/bin/SPIRV/libSPIRV.a vendor/assetImporter/bin/Release/libassetImporter.a vendor/assetImporter/bin/Release/libzlibstatic.a vendor/pamanager/libpamanager/bin/Release/liblibpamanager.a vendor/sdl_mixer/build/Release/libsdl_mixer.a vendor/sdl/build/gmake2--Release/libsdl.a vendor/sdl_mixer/build/Release/liblibvorbis.a vendor/sdl_mixer/build/Release/liblibogg.a vendor/glfw/build/src/libglfw3.a bin/Release/libresource-system-gnu.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s -fno-pie -no-pie

else ifeq ($(config),dist)
TARGETDIR = bin/Dist
TARGET = $(TARGETDIR)/lucre
OBJDIR = bin-int/Dist/Dist/lucre
DEFINES += -DLUCRE_VERSION=\"0.4.2\" -DPULSEAUDIO -DLINUX -DNDEBUG -DDISTRIBUTION_BUILD
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20 -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter -Wno-reorder -Wno-expansion-to-defined
LIBS += bin/Dist/libengine.a vendor/yaml-cpp/build/libyaml-cpp.a vendor/fastgltf/bin/Dist/libfastgltf.a vendor/ufbx/bin/Dist/libufbx.a vendor/box2d/bin/Dist/libbox2d.a vendor/shaderc/bin/shaderc/libshaderc.a vendor/shaderc/bin/shaderc_util/libshaderc_util.a vendor/shaderc/bin/SPIRV-Tools-opt/libSPIRV-Tools-opt.a vendor/shaderc/bin/SPIRV-Tools/libSPIRV-Tools.a vendor/shaderc/bin/MachineIndependent/libMachineIndependent.a vendor/shaderc/bin/OSDependent/libOSDependent.a vendor/shaderc/bin/GenericCodeGen/libGenericCodeGen.a vendor/shaderc/bin/OGLCompiler/libOGLCompiler.a vendor/shaderc/bin/SPIRV/libSPIRV.a vendor/assetImporter/bin/Dist/libassetImporter.a vendor/assetImporter/bin/Dist/libzlibstatic.a vendor/pamanager/libpamanager/bin/Dist/liblibpamanager.a vendor/sdl_mixer/build/Dist/libsdl_mixer.a vendor/sdl/build/gmake2--Dist/libsdl.a vendor/sdl_mixer/build/Dist/liblibvorbis.a vendor/sdl_mixer/build/Dist/liblibogg.a vendor/glfw/build/src/libglfw3.a bin/Dist/libresource-system-gnu.a -lm -ldl -lvulkan -lpthread -lX11 -lXrandr -lXi -lpulse -lglib-2.0 -lgio-2.0
LDDEPS += bin/Dist/libengine.a vendor/yaml-cpp/build/libyaml-cpp.a vendor/fastgltf/bin/Dist/libfastgltf.a vendor/ufbx/bin/Dist/libufbx.a vendor/box2d/bin/Dist/libbox2d.a vendor/shaderc/bin/shaderc/libshaderc.a vendor/shaderc/bin/shaderc_util/libshaderc_util.a vendor/shaderc/bin/SPIRV-Tools-opt/libSPIRV-Tools-opt.a vendor/shaderc/bin/SPIRV-Tools/libSPIRV-Tools.a vendor/shaderc/bin/MachineIndependent/libMachineIndependent.a vendor/shaderc/bin/OSDependent/libOSDependent.a vendor/shaderc/bin/GenericCodeGen/libGenericCodeGen.a vendor/shaderc/bin/OGLCompiler/libOGLCompiler.a vendor/shaderc/bin/SPIRV/libSPIRV.a vendor/assetImporter/bin/Dist/libassetImporter.a vendor/assetImporter/bin/Dist/libzlibstatic.a vendor/pamanager/libpamanager/bin/Dist/liblibpamanager.a vendor/sdl_mixer/build/Dist/libsdl_mixer.a vendor/sdl/build/gmake2--Dist/libsdl.a vendor/sdl_mixer/build/Dist/liblibvorbis.a vendor/sdl_mixer/build/Dist/liblibogg.a vendor/glfw/build/src/libglfw3.a bin/Dist/libresource-system-gnu.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s -fno-pie -no-pie

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/UI.o
GENERATED += $(OBJDIR)/UIControllerIcon.o
GENERATED += $(OBJDIR)/appSettings.o
GENERATED += $(OBJDIR)/application.o
GENERATED += $(OBJDIR)/beachScene.o
GENERATED += $(OBJDIR)/characterAnimation.o
GENERATED += $(OBJDIR)/common.o
GENERATED += $(OBJDIR)/controllerSetup.o
GENERATED += $(OBJDIR)/controllerSetupAnimation.o
GENERATED += $(OBJDIR)/credits.o
GENERATED += $(OBJDIR)/cutScene.o
GENERATED += $(OBJDIR)/dessertScene.o
GENERATED += $(OBJDIR)/duckScript.o
GENERATED += $(OBJDIR)/entryPoint.o
GENERATED += $(OBJDIR)/gameState.o
GENERATED += $(OBJDIR)/gamepadInputController.o
GENERATED += $(OBJDIR)/imgui.o
GENERATED += $(OBJDIR)/infoMessage.o
GENERATED += $(OBJDIR)/island2Scene.o
GENERATED += $(OBJDIR)/keyboardInputController.o
GENERATED += $(OBJDIR)/lucre.o
GENERATED += $(OBJDIR)/mainScene.o
GENERATED += $(OBJDIR)/mainSceneModels.o
GENERATED += $(OBJDIR)/mainSceneRuntime.o
GENERATED += $(OBJDIR)/mainScreen.o
GENERATED += $(OBJDIR)/nightScene.o
GENERATED += $(OBJDIR)/offDialog.o
GENERATED += $(OBJDIR)/reserved0Scene.o
GENERATED += $(OBJDIR)/settingsScene.o
GENERATED += $(OBJDIR)/settingsScreen.o
GENERATED += $(OBJDIR)/snow.o
GENERATED += $(OBJDIR)/splashScene.o
GENERATED += $(OBJDIR)/stars.o
GENERATED += $(OBJDIR)/terrainScene.o
GENERATED += $(OBJDIR)/volcanoScene.o
OBJECTS += $(OBJDIR)/UI.o
OBJECTS += $(OBJDIR)/UIControllerIcon.o
OBJECTS += $(OBJDIR)/appSettings.o
OBJECTS += $(OBJDIR)/application.o
OBJECTS += $(OBJDIR)/beachScene.o
OBJECTS += $(OBJDIR)/characterAnimation.o
OBJECTS += $(OBJDIR)/common.o
OBJECTS += $(OBJDIR)/controllerSetup.o
OBJECTS += $(OBJDIR)/controllerSetupAnimation.o
OBJECTS += $(OBJDIR)/credits.o
OBJECTS += $(OBJDIR)/cutScene.o
OBJECTS += $(OBJDIR)/dessertScene.o
OBJECTS += $(OBJDIR)/duckScript.o
OBJECTS += $(OBJDIR)/entryPoint.o
OBJECTS += $(OBJDIR)/gameState.o
OBJECTS += $(OBJDIR)/gamepadInputController.o
OBJECTS += $(OBJDIR)/imgui.o
OBJECTS += $(OBJDIR)/infoMessage.o
OBJECTS += $(OBJDIR)/island2Scene.o
OBJECTS += $(OBJDIR)/keyboardInputController.o
OBJECTS += $(OBJDIR)/lucre.o
OBJECTS += $(OBJDIR)/mainScene.o
OBJECTS += $(OBJDIR)/mainSceneModels.o
OBJECTS += $(OBJDIR)/mainSceneRuntime.o
OBJECTS += $(OBJDIR)/mainScreen.o
OBJECTS += $(OBJDIR)/nightScene.o
OBJECTS += $(OBJDIR)/offDialog.o
OBJECTS += $(OBJDIR)/reserved0Scene.o
OBJECTS += $(OBJDIR)/settingsScene.o
OBJECTS += $(OBJDIR)/settingsScreen.o
OBJECTS += $(OBJDIR)/snow.o
OBJECTS += $(OBJDIR)/splashScene.o
OBJECTS += $(OBJDIR)/stars.o
OBJECTS += $(OBJDIR)/terrainScene.o
OBJECTS += $(OBJDIR)/volcanoScene.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking lucre
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning lucre
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/application.o: application/application.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/entryPoint.o: application/entryPoint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UI.o: application/lucre/UI/UI.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UIControllerIcon.o: application/lucre/UI/UIControllerIcon.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/common.o: application/lucre/UI/common.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui.o: application/lucre/UI/imgui.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/infoMessage.o: application/lucre/UI/infoMessage.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mainScreen.o: application/lucre/UI/mainScreen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/offDialog.o: application/lucre/UI/offDialog.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/settingsScreen.o: application/lucre/UI/settingsScreen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/controllerSetup.o: application/lucre/UI/settingsTabs/controllerSetup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/controllerSetupAnimation.o: application/lucre/UI/settingsTabs/controllerSetupAnimation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/credits.o: application/lucre/UI/settingsTabs/credits.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stars.o: application/lucre/UI/stars.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/appSettings.o: application/lucre/appSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gameState.o: application/lucre/gameState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gamepadInputController.o: application/lucre/gamepadInputController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/keyboardInputController.o: application/lucre/keyboardInputController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/lucre.o: application/lucre/lucre.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/snow.o: application/lucre/particleSystem/snow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/beachScene.o: application/lucre/scenes/beachScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/characterAnimation.o: application/lucre/scenes/characterAnimation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cutScene.o: application/lucre/scenes/cutScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dessertScene.o: application/lucre/scenes/dessertScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/island2Scene.o: application/lucre/scenes/island2Scene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mainScene.o: application/lucre/scenes/mainScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mainSceneModels.o: application/lucre/scenes/mainSceneModels.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mainSceneRuntime.o: application/lucre/scenes/mainSceneRuntime.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/nightScene.o: application/lucre/scenes/nightScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/reserved0Scene.o: application/lucre/scenes/reserved0Scene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/settingsScene.o: application/lucre/scenes/settingsScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/splashScene.o: application/lucre/scenes/splashScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/terrainScene.o: application/lucre/scenes/terrainScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/volcanoScene.o: application/lucre/scenes/volcanoScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/duckScript.o: application/lucre/scripts/duck/duckScript.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif